#!/bin/sh

set -e # to exit as soon as there is an error

# all functions below are executed in the current directory
# and let the current directory unchanged upon completion

line() { echo '------------------------------------------------------------'; }

start() {
    line
    echo STAGE $stage: $* ...
}

#usage: checkout_commit url commit
checkout_commit() {
    d=`basename $1 .git`
    start install $d
    git clone $1
    cd $d
    git checkout $2
    cd ..
}

#usage: install package_name version
install() {
    start install $1
    opam install -y $1.$2
}

create_opam_switch() {
    start create opam switch
    opam update
    opam switch create . $ocaml_version
}

install_hollight_deps() {
    start install HOL-Light dependencies
    opam pin -y camlp5 $camlp5_version
    opam install -y --deps-only hol_light.$hollight_version
}

install_lambdapi() {
    checkout_commit https://github.com/Deducteam/lambdapi.git $lambdapi_commit
    cd lambdapi
    git checkout -b reproduce
    opam install -y .
    cd ..
}

install_deps() {
    start install dependencies
    opam repo add rocq-released https://rocq-prover.org/opam/released
    opam install -y --deps-only ..
}

install_hol2dk() {
    checkout_commit https://github.com/Deducteam/hol2dk.git $hol2dk_commit
    cd hol2dk
    dune build && dune install
    cd ..
}

install_hollight() {
    checkout_commit https://github.com/jrh13/hol-light.git $hollight_commit
    cd hol-light
    make
    cd ..
}

patch_hollight() {
    start patch hol-light
    hol2dk patch
}

gen_hollight_file() {
    awk "/^loads \"real.ml\"/{print;RM=1;next}/^loads /{if(RM)next}{print}" hol_lib.ml > hol_lib_upto_real.ml
    sed -e "s/hol_lib.ml/hol_lib_upto_real.ml/" hol.ml > $hollight_file
}

dump_proofs() {
    start dump hol-light proofs
    cd hol-light
    gen_hollight_file
    hol2dk dump-simp$dump_simp_option $hollight_file
    cd ..
}

config_output_dir() {
    start configure output directory
    mkdir -p output
    cd output
    if test -f Makefile; then make $jobs clean-all; fi
    hol2dk config $hollight_file $root_path $require $vfiles $mkfile $lpfile
    cd ..
}

translate_proofs() {
    start translate HOL-Light proofs to lambdapi and rocq
    cd output
    make split
    make $jobs lp
    make $jobs v
    make $jobs merge-spec-files
    make $jobs rm-empty-deps
    cd ..
}

check_proofs() {
    start check proofs
    cd output
    make $jobs vo
    cd ..
}

remove_empty_modules() {
    sed -e "s/${base}_//g" \
        -e "/^Require \(Im\|Ex\)port ${root_path}\.theory_hol\.$/d" \
        -e "/^Require \(Im\|Ex\)port ${root_path}\.types\.$/d" \
        -e "/^Require \(Im\|Ex\)port ${root_path}\.axioms\.$/d" \
        $1
}

create_and_check_opam_library() {
    start create opam library
    cd output
    make $jobs opam
    cd ..
    mkdir -p opam
    cd opam
    if test -f Makefile; then make $jobs clean; fi
    cp ../../opam ../../Makefile $vfiles $mkfile .
    remove_empty_modules ../output/${base}_terms.v > terms.v
    remove_empty_modules ../output/${base}_opam.v > theorems.v
    sed -i -e 's/NUMERAL //g' -e 's/(N0)/N0/g' terms.v theorems.v
    make $jobs
    cd ..
}

compare_opam_file() {
    line
    echo compare $1 ...
    diff ../$1 opam/$1
}

compare_opam_files() {
    for f in terms.v theorems.v
    do
        compare_opam_file $f
    done
}

stage() {
    if test $1 -eq $stage
    then
        shift
        $*
        echo $stage > STAGE
        stage=`expr $stage + 1`
    fi
}

set_stage() {
    if test -n "$1"
    then
        stage=$1
    else
        if test -f STAGE
        then
            stage=`head -n1 STAGE` # last completed stage
            stage=`expr $stage + 1`
        else
            stage=1
        fi
    fi
}
